url: https://y7kim.github.io

# Site settings
title: Carlson McKinnon Consulting
copyright: Carlson McKinnon Consulting, LLC
copyright-start: 2015
description: "Small business consulting, navigating the waters of small business for you. We offer consulting services that cover a wide range of small business needs. We can help you get off the ground from the very beginning or help out later on to guide you to further success. Services include: website design, brand design, SEO, mobile app development, legal work, and taxes."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: C1E1A6
  secondary: FF9009
  secondary-dark: 118C4E
  dark: 118C4E

# Team names, titles and social links
people:
- name: Troy McKinnon
  subtitle: Principal and Co-Founder
  modal-id: team-1
  pic: tm.jpg

-

- name: Austin Calrson
  subtitle: Principal and Co-Founder
  modal-id: team-2
  pic: ac.png

# Build settings
markdown: kramdown
permalink: pretty
