- title: Small Business Consultation
  subtitle: Providing necessary guidance
  content: consultation.md
  icon: building
  modal-id: service-1
  service: true

- title: Web Design and SEO
  subtitle: High quality web presence
  content: web.md
  icon: internet-explorer
  modal-id: service-2
  service: true

- title: Branding
  subtitle: Distinguish yourself
  content: branding.md
  icon: paint-brush
  modal-id: service-3
  service: true

- title: Mobile App Development
  subtitle: Go native mobile
  content: mobile.md
  icon: mobile
  modal-id: service-4
  service: true

- title: Entity Selection
  subtitle: Understanding types of legal entities
  content: entity.md
  icon: gavel
  modal-id: service-5
  service: true

- title: Small Business 101
  subtitle: Helpful Links
  content: links.md
  icon: link
  modal-id: service-6
  service: true

- title: Troy McKinnon
  subtitle: Principal and Co-Founder
  content: tm.md
  modal-id: team-1
  pic: tm.jpg

- title: Austin Carlson
  subtitle: Principal and Co-Founder
  content: ac.md
  modal-id: team-2
  pic: ac.png
